---
AWSTemplateFormatVersion: 2010-09-09

Description: Create DynamoDB Table

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Select environment.
    AllowedValues:
    - prod
    - dev

Resources:
  KomatchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}-komatch"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: data_type
          AttributeType: S
        - AttributeName: data_value
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: data_type
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: data_value
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
