---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Mappings:
  EnvMap:
    prod:
      ApiGatewayModelName: ProdKomatchSchema
    dev:
      ApiGatewayModelName: DevKomatchSchema
    dev1:
      ApiGatewayModelName: Dev1KomatchSchema
    dev2:
      ApiGatewayModelName: Dev2KomatchSchema
    dev3:
      ApiGatewayModelName: Dev3KomatchSchema

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Select environment.
    AllowedValues:
    - prod
    - dev
    - dev1
    - dev2
    - dev3

Resources:
  # API Gateway RestAPI
  SlackApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${Env}_KomatchApi"
      Description: !Sub "${Env} komatch api"
  # API Gateway Deployment
  # it depends on API Gateway Method
  SlackApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: SlackApiGatewayMethod
    Properties:
      RestApiId:
        Ref: SlackApiGatewayRestApi
      Description: apigateway deployment
  # API Gateway Stage
  # it depends on API Gateway Deployment
  SlackApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Sub "${Env}"
      Description: !Sub "${Env} stage"
      RestApiId:
        Ref: SlackApiGatewayRestApi
      DeploymentId:
        Ref: SlackApiGatewayDeployment
  # API Gateway Model
  SlackApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId:
        Ref: SlackApiGatewayRestApi
      ContentType: application/json
      Description: !Sub "Schema for ${Env} Komatch"
      Name: !FindInMap [EnvMap, Ref: Env, ApiGatewayModelName]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        title: PetsModelNoFlatten
        type: object
        properties:
          status:
            type: string
          message:
            type: string
  # API Gateway Resource
  SlackApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: SlackApiGatewayRestApi
      ParentId:
        Fn::GetAtt:
          - SlackApiGatewayRestApi
          - RootResourceId
      PathPart: komatch
  # API Gateway Method
  SlackApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Ref: SlackApiGatewayRestApi
      ResourceId:
        Ref: SlackApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway
              - ":"
              - Ref: AWS::Region
              - ":"
              - lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                - IndexLambdaFunction
                - Arn
              - /invocations
        IntegrationHttpMethod: POST
        IntegrationResponses:
          -
            StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/x-www-form-urlencoded: "{\n \"body\" : $input.json('$')\n}"
      MethodResponses:
        -
          StatusCode: 200
          ResponseModels:
            application/json: Empty
  # API Gateway UsagePlan
  SlackApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        -
          ApiId:
            Ref: SlackApiGatewayRestApi
          Stage:
            Ref: SlackApiGatewayStage
      Quota:
        Limit: 100
        Period: DAY
      Throttle:
        BurstLimit: 10
        RateLimit: 2
      Description: !Sub "${Env} komatch api usage plan"
      UsagePlanName: !Sub "${Env}_KomatchUsagePlan"

  # Lambda Function
  IndexLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_index"
      Environment:
        Variables:
          env: !Sub "${Env}"
          STEP_FUNCTIONS_ARN: !GetAtt TestStateMachine.Arn
          RECEIVE_REACTION_FUNCTION_NAME: !Ref ReceiveReactionFunction
          SOLVE_QUESTION_FUNCTION_NAME: !Ref SolveQuestionFunction
      Handler: index.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/index
      Role: !GetAtt IndexLambdaIAMRole.Arn
      Timeout: 10
      Layers:
        - !Ref LibsLayer

  # Lambda Permission
  IndexLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
         Fn::GetAtt:
          - IndexLambdaFunction
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - arn:aws:execute-api
            - ":"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: SlackApiGatewayRestApi
            - /*/*/*

  ExtractKeywordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_extract_keywords"
      Handler: comprehend.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/extract_keywords
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Timeout: 10

  GetUsersLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_get_users"
      Handler: get_users.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/get_users
      Layers:
        - !Ref LibsLayer
      Environment:
        Variables:
          DDB_TABLE:
            Fn::ImportValue: !Sub "${Env}-DynamoDBTable"
          env: !Sub "${Env}"
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Timeout: 10
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(24 hours)

  RegisterQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_register_question"
      Handler: register_question.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/register_question
      Layers:
        - !Ref LibsLayer
      Environment:
        Variables:
          DDB_TABLE:
            Fn::ImportValue: !Sub "${Env}-DynamoDBTable"
          env: !Sub "${Env}"
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Timeout: 10

  RecommendUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_recommend_users"
      Handler: recommend_users.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/recommend_users
      Layers:
        - !Ref LibsLayer
      Environment:
        Variables:
          DDB_TABLE:
            Fn::ImportValue: !Sub "${Env}-DynamoDBTable"
          env: !Sub "${Env}"
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Timeout: 10

  ReceiveReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_receive_reaction"
      Handler: receive_reaction.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/receive_reaction
      Layers:
        - !Ref LibsLayer
      Environment:
        Variables:
          DDB_TABLE:
            Fn::ImportValue: !Sub "${Env}-DynamoDBTable"
          env: !Sub "${Env}"
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Timeout: 10

  SolveQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_solve_question"
      Handler: solve_question.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/solve_question
      Layers:
        - !Ref LibsLayer
      Environment:
        Variables:
          DDB_TABLE:
            Fn::ImportValue: !Sub "${Env}-DynamoDBTable"
          env: !Sub "${Env}"
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Timeout: 10

  # Layer
  LibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib
      Description: ruby library
      ContentUri: ../lib/.
      CompatibleRuntimes:
        - ruby2.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  MessengerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}_Komatch_messenger"
      Handler: messenger.handler
      MemorySize: 128
      Runtime: ruby2.7
      CodeUri: ../src/messenger
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Layers:
        - !Ref LibsLayer
      Environment:
        Variables:
          DDB_TABLE:
            Fn::ImportValue: !Sub "${Env}-DynamoDBTable"
          env: !Sub "${Env}"
      Timeout: 10

  # StepFunctions
  TestStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${Env}-StateMachine
      RoleArn:
        Fn::GetAtt: [ StatesExecutionRole, Arn ]
      DefinitionString:
        Fn::Sub:
          |-
            {
              "StartAt": "ExtractKeywords",
              "States": {
                "ExtractKeywords": {
                  "Type": "Task",
                  "Resource": "${ExtractKeywordsFunction.Arn}",
                  "ResultPath":"$.keywords",
                  "OutputPath": "$",
                  "Next": "RegisterQuestion"
                },
                "RegisterQuestion": {
                  "Type": "Task",
                  "Resource": "${RegisterQuestionFunction.Arn}",
                  "ResultPath":"$.question_id",
                  "OutputPath": "$",
                  "Next": "RecommendUsers"
                },
                "RecommendUsers": {
                  "Type": "Task",
                  "InputPath":"$.question_id",
                  "Resource": "${RecommendUsersFunction.Arn}",
                  "ResultPath":"$.user_ids",
                  "OutputPath": "$",
                  "Next": "Messenger"
                },
                "Messenger": {
                  "Type": "Task",
                  "Resource": "${MessengerFunction.Arn}",
                  "End": true
                }
              }
            }

  # Index Lambda 以外のLambda用の IAM Role
  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchAccessFromLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: DynamoDBAccessFromLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Describe*
                  - dynamodb:List*
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                Resource: "*"
        - PolicyName: SystemManagerAccessFromLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:Describe*
                  - ssm:Get*
                  - ssm:List*
                Resource: "*"
        - PolicyName: ComprehendAccessFromLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - comprehend:Detect*
                Resource: "*"

  # Index Lambda 用の IAM Role
  IndexLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchAccessFromLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SystemManagerAccessFromLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:Describe*
                  - ssm:Get*
                  - ssm:List*
                Resource: "*"
        - PolicyName: StartExecution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: "*"
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  # StepFunctions用のIAMロール
  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
