---
AWSTemplateFormatVersion: "2010-09-09"

Description: Create S3 Bucket

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Select environment.
    AllowedValues:
    - prod
    - dev
    - dev1
    - dev2
    - dev3

Resources:
  S3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${Env}-komatch"
