---
AWSTemplateFormatVersion: 2010-09-09

Description: Create DynamoDB Table

Mappings:
  EnvMap:
    prod:
      DynamoDBTableName: ProdKomatch
    dev:
      DynamoDBTableName: DevKomatch
    dev1:
      DynamoDBTableName: Dev1Komatch
    dev2:
      DynamoDBTableName: Dev2Komatch
    dev3:
      DynamoDBTableName: Dev3Komatch

Parameters:
  Env:
    Type: String
    Default: dev
    Description: Select environment.
    AllowedValues:
    - prod
    - dev
    - dev1
    - dev2
    - dev3

Resources:
  KomatchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [EnvMap, Ref: Env, DynamoDBTableName]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: data_type
          AttributeType: S
        - AttributeName: data_value
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: data_type
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: data_value
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST

Outputs:
  Dynamodb:
    Value: !Ref KomatchTable
    Export:
      Name: !Sub ${Env}-DynamoDBTable
